package org.example.enumerations;

public enum SagaState {
    STARTED,
    ROOM_RESERVED,
    ROOM_RESERVATION_FAILED,
    PAYMENT_AUTHORIZED,
    PAYMENT_AUTHORIZATION_FAILED,
    BOOKING_COMPLETED,
    BOOKING_CANCELLED,
    COMPENSATING,
    COMPENSATION_COMPLETED,
    COMPENSATION_FAILED
}